### ISSUE TITLE
Incorrect link to scrubbed database?

### ISSUE THREAD

**Issue by quartertone** [LibriVox/librivox-ansible#14]
The README of librivox-ansible and CONTRIBUTING.md page of librivox-catalog links to

https://github.com/LibriVox/librivox-ansible/blob/master/roles/blog%2Bcatalog/files/librivox_catalog_scrubbed.sql.bz2

but it looks like the file is now at

https://github.com/LibriVox/librivox-ansible/blob/master/resources/librivox_catalog_scrubbed.sql.bz2

Is this the right file?

**Comment by notartom** [comment]
Yep, that's the one. I was sure I updated the link in the docs...

**Comment by notartom** [comment]
Fixed by https://github.com/LibriVox/librivox-ansible/commit/8670235ee5a198c74afbc41c4b93febbfb64ba71
