### ISSUE TITLE
Emails not being sent by wiki server

### ISSUE THREAD

**Issue by quartertone** [LibriVox/librivox-ansible#15]
Any attempt to have the wiki server send email results in a `Unknown error in PHP's mail() function.` message.

Examples:

[Requesting a confirmation code](https://wiki.librivox.org/index.php?title=Special:ConfirmEmail) on a newly created wiki account does not work:

> Librivox wiki could not send your confirmation mail. Please check your email address for invalid characters.
> 
> Mailer returned: Unknown error in PHP's mail() function.

[Changing email address](https://wiki.librivox.org/index.php?title=Special:ChangeEmail) through the user preferences page gives a similar error:

>Unknown error in PHP's mail() function.

[Requesting a password reset](https://wiki.librivox.org/index.php?title=Special:PasswordReset) fails silently.

**Comment by quartertone** [comment]
Ha! I was just about to suggest the fix but you beat me to it.

**Comment by notartom** [comment]
I had to set up the SMTP user in the relay service too, so I had to be involved regardless :)
